config/routes.rb
Rails.application.routes.draw do
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :contacts
  
  resources :verticals
  
  resources :businesses do
    
    resources :phase1s do
        resources :headers, shallow: true
    end
    
    resources :phase2s
    resources :phase3s
    resources :phase4s
  end
  
  get '/dashboard' => 'pages#dashboard'
  get '/settings' => 'pages#settings'
  get '/help' => 'pages#help'
  get '/display' => 'pages#display'
  get '/phase1' => 'phase1s#index'
  get '/phase2' => 'phase2s#index'
  get '/phase3' => 'phase3s#index'
  get '/phase4' => 'phase4s#index'
  
  root 'user_sessions#new'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
    
    def index
        @businesses = Business.order(:id).reverse
       
        if params[:search]
            @businesses = Business.search(params[:search]).order(:id).reverse
        else
            @businesses = Business.all.order(:id).reverse
        end
    end
    
    def new
        @business = Business.new
    end
    
    def create
        @business = Business.new(business_params)
        
        if @business.save
            flash[:success] = "Business added."
            redirect_to @business
        else
            errorString = "Error occured, business not added."
            
            @business.errors.each do |attribute, error|
                errorString = "#{errorString}" + " #{attribute}" + " #{error}"
            end
            
            flash[:alert] = errorString.html_safe
            redirect_to businesses_url
        end
    end
    
    def show
        @business = Business.find( params[:id] )
    end
    
    def edit
        @business = Business.find( params[:id] )
    end
    
    def update
        @business = Business.find( params[:id] )
        
        if @business.update_attributes(business_params)
            flash[:success] = "Profile updated"
            redirect_to @business
        else
            flash[:alert] = "Profile not updated"
            redirect_to @business
        end
    end

    def destroy 
        @business = Business.find( params[:id] ) 
        @business.destroy
        
        flash[:success] = "Business deleted"
        redirect_to businesses_url
    end
    
    private
        def business_params
            params.require(:business).permit(:name, :vertical, :address, :url, :branding)
        end
    
end

app/views/businesses/_count.html.erb
<div class="callout card count clearfix">
    <div class="count-icon float-left">
        <i class="fa fa-briefcase fa-fw"></i>        
    </div>
    <div>
        <h6>Total Businesses</h6>
        <div class="stat"><%= link_to Business.count, businesses_path, class: 'no-link' %></div>
    </div>
</div>

app/views/businesses/_latest.html.erb
 <div class="callout card">
            
    <div class="callout-header">
        <% if (current_user.userrank == 'admin') || (current_user.userrank == 'seo')  %>
            <%= link_to '<i class="fa fa-plus-circle fa-fw" aria-hidden="true"></i> New'.html_safe,  new_business_path, class: "button secondary small float-right" %>
        <% end %>
        <h4>Latest Businesses</h4>
    </div>
    <div class="callout-table">
        <table>
        
         <%  @business = Business.last(5).reverse %>
         
          <% @business.each do |business| %>
                <tr>
                    <td class="narrow"><div class="icon-circle"><i class="fa fa-briefcase fa-fw"></i></div></td>
                    <td>
                        <%= business.name %><br>
                        <small class="time-ago"><i class="fa fa-clock-o" aria-hidden="true"></i> <%= time_ago_in_words(business.created_at) %> ago</small>
                    </td>
                    <td class="text-right">
                       
                        <%= link_to '<i class="fa fa-ellipsis-v fa-fw"></i>'.html_safe, business %>
                       
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
    <div class="callout-footer">
        <%= link_to 'See all Businesses',  businesses_path, class: 'card expanded link' %>
    </div>
</div>

app/views/businesses/_mobile.html.erb
<% @business = Business.where(:id => @phase1.business_id).first %>

<div class="mobileFriendiness text-center">
    <div class="row">
        <div class="small-12 columns">
          <h1>Mobile Friendliness</h1>  
            
            <div class="desktop">
                <iframe src="<%= @business.url %>"></iframe>
            </div>
            
            <div class="pageBreak"></div>

            <div class="tablet">
                <iframe src="<%= @business.url %>"></iframe>
            </div>
            
            <div class="pageBreak"></div>

            <div class="phone">
                <iframe src="<%= @business.url %>"></iframe>
            </div>
            
        </div>
    </div>
</div>

app/views/businesses/edit.html.erb
<div class="page-title">
    <h1><%= @business.name %></h1>
    <nav aria-label="You are here:" role="navigation">
      <ul class="breadcrumbs">
        <li><%= link_to 'Businesses',  businesses_path %></li>
        <li><%= link_to @business.name, @business %></li>
        <li>
          <span class="show-for-sr">Current: </span> Editing
        </li>
      </ul>
    </nav>
</div>

<div class="callout card">
    <div class="callout-header">
        <h4>Edit Business Stats</h4>
    </div>
    
    <div class="callout-table">
       
            <%= form_for @business, method: :patch do |f| %>
                <table>
                    <tr>
                        <th><%= f.label :name %></th>
                        <td><%= f.text_field :name %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :vertical %></th>
                        <td><%= f.select(:vertical, options_from_collection_for_select(Vertical.all, "name", "name", @business.vertical)) %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :address %></th>
                        <td><%= f.text_field :address %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :url %></th>
                        <td><%= f.text_field :url %></td>
                    </tr>
                    <tr>
                        <td><%= f.submit 'Submit', class: "button secondary" %></td>
                    </tr>
                </table>
            <% end %>
       
        
        
    </div>
</div>
        

app/views/businesses/index.html.erb
<div class="page-title">
    <h1>Businesses</h1>
    <nav aria-label="You are here:" role="navigation">
      <ul class="breadcrumbs">
        <li><%= link_to 'Businesses',  businesses_path %></li>
        <li>
          <span class="show-for-sr">Current: </span> 
          
              <% if params[:search] %>
                  Search: <%= params[:search] %>
              <% else %>
                  All
              <% end %>
        </li>
      </ul>
    </nav>
</div>

<div class="callout card">
    <div class="callout-header">
        <%= link_to '<i class="fa fa-plus-circle fa-fw" aria-hidden="true"></i> New'.html_safe,  new_business_path, class: "button secondary small float-right" %>
        <% if params[:search] %>
             Business Search
          <% else %>
              All Businesses
          <% end %>
    </div>
    
<% if @businesses.blank? %>
    <div class="callout-body">
        <h4>There are no businesses containing the term <%= params[:search] %>.</h4>
    </div>
<% else %>
    
    <div class="callout-table">
        
        <table id="filterTable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Vertical</th>
                    <th>Address</th>
                    <th>Url</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            
            <tbody>
                <% @businesses.each do |business| %>
                    <tr>
                        <td><%= link_to business.name, business %></td>
                        <td><%= business.vertical  %></td>
                        <td><%= business.address %></td>
                        <td><%= business.url %></td>
                        <td><%= link_to 'Edit', {:action => "edit", :id => business.id} %></td>
                        <td><%= link_to "Delete", business, method: :destroy,
                                  data: { confirm: "You sure?" } %></td>
                    </tr>
                <% end %>
            </tbody>
            
        </table>
        
        
    </div>
    <% end %>
</div>


<script>
    $(document).ready(function() {
        $('#filterTable').DataTable( {
            "lengthMenu": [ [10, 50, 100, 200,300,400,500,600,700,800,900, -1], [10, 50, 100, 200,300,400,500,600,700,800,900, "All"] ],
            "language": {
                "lengthMenu": "Show _MENU_",
                "search": "Search",
                "paginate": {
                    "next": "&raquo;",
                    "previous": "&laquo;"
                }
            },
            "pagingType": "simple_numbers",
            "columns": [
                null,
                null,
                null,
                null,
                { "orderable": false, "searchable": false },
                { "orderable": false, "searchable": false }
              ]
        });
    });
</script>
   

app/views/businesses/new.html.erb
<div class="page-title">
    <h1>New Business</h1>
    <h4 class="subheader">Add a Business</h4>
</div>


<div class="callout card">
    <div class="callout-header">
        <h4>Business Details</h4>
    </div>
    <div class="callout-table">
        
        <%= form_for @business do |f| %>
            <table>
                <tr>
                    <th><%= f.label :name %></th>
                    <td><%= f.text_field :name %></td>
                </tr>
                    <tr>
                        <th><%= f.label :vertical %></th>
                        <td><%= f.select(:vertical, options_from_collection_for_select(Vertical.all, "name", "name", @business.vertical)) %></td>
                    </tr>
                <tr>
                    <th><%= f.label :address %></th>
                    <td><%= f.text_field :address %></td>
                </tr>
                <tr>
                    <th><%= f.label :url %></th>
                    <td><%= f.text_field :url %></td>
                </tr>
                <tr>
                    <th class="narrow"><%= f.label "Client" %></th>
                    <td>
                        <%= f.radio_button :branding, 'Next' %> 
                        <%= f.label :branding, 'Next', :value => 'Next' %>
                        <%= f.radio_button :branding, 'CGI' %>
                        <%= f.label :branding, 'CGI', :value => 'CGI' %>
                    </td>
                </tr>
                <tr>
                    <td><%= f.submit 'Submit', class: "button secondary" %></td>
                </tr>
                </table>
        <% end %>
        
        

    </div>
</div>

app/views/businesses/show.html.erb
<div class="page-title">
    <h1><%= @business.name %></h1>
    <nav aria-label="You are here:" role="navigation">
      <ul class="breadcrumbs">
        <li><%= link_to 'Businesses',  businesses_path %></li>
        <li>
          <span class="show-for-sr">Current: </span> <%= @business.name %>
        </li>
      </ul>
    </nav>
</div>

<div class="row">
    <div class="medium-7 columns">
        <div class="callout card">
            <div class="callout-header">
                <div class ="float-right">
                    <% if (current_user.userrank == 'admin') || (current_user.userrank == 'seo')  %>
                        <%= link_to '<i class="fa fa-pencil fa-fw" aria-hidden="true"></i> Update'.html_safe,  edit_business_path, class: "button secondary small" %>
                        <%= link_to '<i class="fa fa-trash fa-fw" aria-hidden="true"></i> Delete'.html_safe, @business, class: "button secondary small", method: :delete,
                                      data: { confirm: "You sure?" } %>
                    <% end %>
                </div>

                <h4>Stats</h4>
            </div>
            <div class="callout-table">
                
                <table>
                    <tr>
                        <td class="narrow"><div class="icon-circle"><i class="fa fa-briefcase fa-fw"></i></div></td>
                        <td>
                            <%= @business.name %><br>
                            <small>Business Name</small>
                        </td>
                    </tr>
                    <tr>
                        <td class="narrow"><div class="icon-circle"><i class="fa fa-question fa-fw"></i></div></td>
                        <td>
                            <%= @business.vertical %><br>
                            <small>Business Vertical</small>
                        </td>
                    </tr>
                    <tr>
                        <td class="narrow"><div class="icon-circle"><i class="fa fa-map-marker fa-fw"></i></div></td>
                        <td>
                            <%= @business.address %><br>
                            <small>Business Address</small>
                        </td>
                    </tr>
                    <tr>
                        <td class="narrow"><div class="icon-circle"><i class="fa fa-link fa-fw"></i></div></td>
                        <td>
                            <%= @business.url %><br>
                            <small>Business URL</small>
                        </td>
                    </tr>
                    <tr>
                        <td class="narrow"><div class="icon-circle"><i class="fa fa-link fa-fw"></i></div></td>
                        <td>
                            <%= @business.branding %><br>
                            <small>Client Of</small>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="medium-4 columns">
        <%= render 'phase1s/latestByBusiness' %>
    </div>
    <div class="medium-4 columns">
        <%= render 'phase2s/latestByBusiness' %>
    </div>
    <div class="medium-4 columns">
        <%= render 'phase3s/latestByBusiness' %>
    </div>
</div>

<div class="row">
    <div class="medium-4 columns">
        <%= render 'phase4s/latestByBusiness' %>
    </div>
</div>