config/routes.rb
Rails.application.routes.draw do
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :contacts
  
  resources :verticals
  
  resources :businesses do
    
    resources :phase1s do
        resources :headers, shallow: true
    end
    
    resources :phase2s
    resources :phase3s
    resources :phase4s
  end
  
  get '/dashboard' => 'pages#dashboard'
  get '/settings' => 'pages#settings'
  get '/help' => 'pages#help'
  get '/display' => 'pages#display'
  get '/phase1' => 'phase1s#index'
  get '/phase2' => 'phase2s#index'
  get '/phase3' => 'phase3s#index'
  get '/phase4' => 'phase4s#index'
  
  root 'user_sessions#new'

end

app/models/header.rb
class Header < ActiveRecord::Base
    belongs_to :phase1
end

app/controllers/headers_controller.rb
class HeadersController < ApplicationController
    
    def new
        @business = Business.find(params[:business_id])
        @phase1 = Phase1.find(params[:phase1_id])
        
        @header = Header.new
    end
    
    def create
        @business = Business.find(params[:business_id])
        @phase1 = Phase1.find(params[:phase1_id])
        
       #resultString = "false"
        
        params[:headers].each do |headers_params|
            @header = @phase1.headers.new()
            
            @header.pageName = headers_params[1]['pageName']
            @header.pageTitle = headers_params[1]['pageTitle']
            @header.pageDescript = headers_params[1]['pageDescript']
            @header.h1Tags = headers_params[1]['h1Tags']
            @header.h2Tags = headers_params[1]['h2Tags']
            
            @header.business_id = @business.id
            
            @header.save
            #else
            #    errorString = errorString + "fail"
            #end
            
        end
        
        # if errorString.length 
        #flash[:alert] = "#{resultString}"
        
        
        redirect_to business_phase1_path(@business, @phase1)

    
    end
    
    def show
    end
    
    def edit
        @header = Header.find(params[:id])
        @business = Business.find(@header.business_id)
        @phase1 = Phase1.find(@header.phase1_id)
    end
    
    def update
        @header = Header.find(params[:id])
        @business = Business.find(@header.business_id)
        @phase1 = Phase1.find(@header.phase1_id)
        
        if @header.update_attributes(header_params)
            flash[:success] = "Page updated"
        else
            flash[:alert] = "Page not updated"
        end
        
        redirect_to business_phase1_path(@business, @phase1)
    end
    
    def destroy
        @header = Header.find(params[:id])
        @business = Business.find(@header.business_id)
        @phase1 = Phase1.find(@header.phase1_id)
        
        @header.destroy
        flash[:success] = "Page entry deleted"
        redirect_to business_phase1_path(@business, @phase1)
    end
    
    
    private
        def header_params
            params.require(:header).permit(:pageName, :pageTitle, :pageDescript, :h1Tags, :h2Tags)
        end
    
end

app/views/headers/_addHeaders.html.erb
<div class="callout card">
    <div class="callout-header">
        <h4><i class="fa fa-plus-circle fa-fw" aria-hidden="true"></i> Add Pages</h4>
    </div>
    <div class="callout-body">
        <%= form_tag(new_business_phase1_header_path(@business, @phase1), method: "get") do %>
            <%= label_tag(:q, "Number of new pages:") %>
            <%= select_tag :count, options_for_select(1..15) %>
            
            <div class="text-right">
                <%= submit_tag("Create Pages".html_safe, class: "button secondary small", :name => nil) %>
            </div>
        <% end %>
    </div>
</div>

app/views/headers/_headersByPhase.html.erb
<% @headers = @phase1.headers.all %>

<% if @headers.length %>
 <hr class="phaseHR">
<% end %>

<% @headers.each do |header| %>

 <div class="callout card">
    <div class="callout-header">
        <% if (current_user.userrank == 'admin') || (current_user.userrank == 'seo')  %>
            <div class ="float-right">
                <%= link_to '<i class="fa fa-pencil fa-fw" aria-hidden="true"></i> Edit'.html_safe,  edit_header_path(header.id), class: "button secondary small" %>
                <%= link_to '<i class="fa fa-trash fa-fw" aria-hidden="true"></i> Delete'.html_safe, header, method: :delete, class: "button secondary small" %>
            </div>
        <% end %>
        
        <h4><i class="fa fa-file-o fa-fw" aria-hidden="true"></i> Page: <%= header.pageName %></h4>
    </div>
    <div class="callout-table">
        <table>
            <tr>
                <th class="narrow">Page Name</th>
                <td><%= header.pageName %></td>
            </tr>
            <tr>
                <th class="narrow">Page Title</th>
                <td><%= header.pageTitle %></td>
            </tr>
            <tr>
                <th class="narrow">Description</th>
                <td><%= header.pageDescript %></td>
            </tr>
            <tr>
                <th class="narrow">H1 Tags</th>
                <td><%= header.h1Tags %></td>
            </tr>
            <tr>
                <th class="narrow">H2 Tags</th>
                <td><%= header.h2Tags %></td>
            </tr>
        </table>
        
    </div>
</div>


<% end %>

app/views/headers/_report.html.erb
<% @headers = Header.where(:phase1_id => @phase1.id ) %>

<% @headers.each do |header| %>
    
    <p class="header-report">
        <strong class="blue">Page:</strong> <%= header.pageName %> <br>
        <strong class="blue">New Title:</strong> <%= header.pageTitle %> <br>
        <strong class="blue">New Description:</strong> <%= header.pageDescript %> <br>
        
        <% if header.h1Tags.present? %>
            <strong class="blue">H1:</strong> <%= header.h1Tags %> <br>
        <% end %>
        
        <% if header.h2Tags.present? %>
            <strong class="blue">H2:</strong> <%= header.h2Tags %>
        <% end %>
    </p>

<% end %>

app/views/headers/edit.html.erb
<div class="callout card">
    <div class="callout-header">
        <h4><i class="fa fa-file-o fa-fw" aria-hidden="true"></i> Page Details</h4>
    </div>
    
    
        <%= form_for @header, url: header_path(@header.id), method: :patch do |f| %>
            <div class="callout-table">
                <table>
                    <tr>
                        <th class="narrow"><label>Page Name</label></th>
                        <td><%= f.text_field :pageName %></td>
                    </tr>
                    <tr>
                        <th class="narrow"><label>Page Title</label></th>
                        <td><%= f.text_field :pageTitle %></td>
                    </tr>
                    <tr>
                        <th class="narrow"><label>Description</label></th>
                        <td><%= f.text_area :pageDescript , class: "count-watch" %><span class="meta-count"></span></td>
                    </tr>
                    <tr>
                        <th class="narrow"><label>H1 Tags</label></th>
                        <td><%= f.text_area :h1Tags %></td>
                    </tr>
                    <tr>
                        <th class="narrow"><label>H2 Tags</label></th>
                        <td><%= f.text_area :h2Tags %></td>
                    </tr>
                </table>
            </div>
        
            <div class="callout-footer padded">
                <%= f.submit 'Submit', class: "button secondary" %>
            </div>
        <% end %>
</div>

<script>
    $(document).ready(function() {
        $('.count-watch').on('keyup', function(event) {
            $(this).siblings( ".meta-count" ).text($(this).val().length);
        });
        
        $(".meta-count").text($( ".count-watch" ).val().length);
    });
</script>

app/views/headers/new.html.erb
<div class="page-title">
    <h1><%= @business.name %> Page Headers</h1>
    <nav aria-label="You are here:" role="navigation">
      <ul class="breadcrumbs">
        <li><%= link_to 'Businesses',  businesses_path %></li>
        <li><%= link_to @business.name, business_path(@business) %></li>
        <li><%= link_to 'Phase 1',  business_phase1_path(@business, @phase1) %></li>
        <li>
          <span class="show-for-sr">Current: </span> New Headers
        </li>
      </ul>
    </nav>
</div>



<%= form_tag business_phase1_headers_path(@business, @phase1) do %>
<% count = params[:count].to_i %>
<% count.to_i.times do |x| %>
    <div class="callout card">
        <div class="callout-header">
            <h4>Page <%= x + 1 %> Details</h4>
        </div>
        <div class="callout-table">
            <table>
                <tr>
                    <th class="narrow"><label>Page Name</label></th>
                    <td><%= text_field_tag :headers_pageName, "", :name => "headers[#{x}][pageName]" %></td>
                </tr>
                <tr>
                    <th class="narrow"><label>Page Title</label></th>
                    <td><%= text_field_tag :headers_pageTitle, "", :name => "headers[#{x}][pageTitle]" %></td>
                </tr>
                <tr>
                    <th class="narrow"><label>Description</label></th>
                    <td><%= text_area_tag :headers_pageDescript, "", :name => "headers[#{x}][pageDescript]", class: "count-watch" %><span class="meta-count"></span></td>
                </tr>
                <tr>
                    <th class="narrow"><label>H1 Tags</label></th>
                    <td><%= text_area_tag :headers_h1Tags, "", :name => "headers[#{x}][h1Tags]" %></td>
                </tr>
                <tr>
                    <th class="narrow"><label>H2 Tags</label></th>
                    <td><%= text_area_tag :headers_h2Tags, "", :name => "headers[#{x}][h2Tags]" %></td>
                </tr>
            </table>
            
        </div>
    </div>

<% end %>

<div class="callout card">
    <div class="callout-header">
        <h4>Submit</h4>
    </div>
    <div class="callout-body">
        <%= submit_tag("Submit".html_safe, class: "button secondary small", :name => nil) %>
    </div>
</div>

<% end %>


<script>
    $(document).ready(function() {
        $('.count-watch').on('keyup', function(event) {
            $(this).siblings( ".meta-count" ).text($(this).val().length);
        });
        
        $(".meta-count").text($( ".count-watch" ).val().length);
    });
</script>