config/routes.rb
Rails.application.routes.draw do
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :contacts
  
  resources :verticals
  
  resources :businesses do
    
    resources :phase1s do
        resources :headers, shallow: true
    end
    
    resources :phase2s
    resources :phase3s
    resources :phase4s
  end
  
  get '/dashboard' => 'pages#dashboard'
  get '/settings' => 'pages#settings'
  get '/help' => 'pages#help'
  get '/display' => 'pages#display'
  get '/phase1' => 'phase1s#index'
  get '/phase2' => 'phase2s#index'
  get '/phase3' => 'phase3s#index'
  get '/phase4' => 'phase4s#index'
  
  root 'user_sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= favicon_link_tag 'favicon.ico' %>
    
    <title><%= content_for?(:title) ? yield(:title) : "SEO Report" %></title>

    <%= stylesheet_link_tag    "application", media: "screen, print" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Oswald|Roboto:400,400italic|Roboto+Condensed' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    
			  
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.js"></script>

  </head>

  <body>
    
  <div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
      <div class="off-canvas position-left reveal-for-medium" id="offCanvas" data-off-canvas>

        <!-- Close button -->
        <button class="close-button show-for-small-only" aria-label="Close menu" type="button" data-close>
          <span aria-hidden="true">&times;</span>
        </button>
        
        <div class="title">
          
          <%= link_to(image_tag("logo.png", :alt => "logo", :title => "Home"), dashboard_path ) %>
          
        </div>
        
        <div class="user-info">
          <i class="fa fa-user fa-4x" aria-hidden="true"></i>
          
          <% if current_user %>
            <h5>Welcome <%= current_user.username %>!</h5>
            <h6 class="subheader"><%= current_user.userrank %></h6>
          <% end %>
          
        </div>

        <!-- Menu -->
        <ul class="vertical menu">
          <li><%= link_to '<i class="fa fa-tachometer fa-fw" aria-hidden="true"></i> Dashboard'.html_safe, dashboard_path, class: cp(dashboard_path) %></li>
          <li><%= link_to '<i class="fa fa-briefcase fa-fw" aria-hidden="true"></i> Businesses'.html_safe, businesses_path, class: cp(businesses_path)  %></li>
          <li><%= link_to '<i class="fa fa-cog fa-fw" aria-hidden="true"></i> Settings'.html_safe, settings_path, class: cp(settings_path) %></li>
          <li><%= link_to '<i class="fa fa-user fa-fw" aria-hidden="true"></i> Profile'.html_safe,  user_path(current_user.id) %></li>
          <li><%= link_to '<i class="fa fa-question-circle fa-fw" aria-hidden="true"></i> Help'.html_safe, help_path, class: cp(help_path) %></li>
          <li><%= link_to '<i class="fa fa-comments fa-fw" aria-hidden="true"></i> Contact'.html_safe,  new_contact_path, class: cp(new_contact_path) %></li>
        </ul>

      </div>

      <div class="off-canvas-content" data-off-canvas-content>
        
        <!-- top-bar -->
        <div class="title-bar">
          <div class="title-bar-left">
              <ul class="menu">
            <!--<li><button class="menu-icon" type="button" data-open="offCanvas"></button></li>-->
            <li><a data-open="offCanvas"><i class="fa fa-bars fa-fw"></i></a></li>
           <li class="show-for-small-only"><span class="title-bar-title">SEO Report</span></li>
           
           <li class="no-border">
             <div class="search">
              <%= form_tag(businesses_path, :method => "get", id: "search-form") do %>
                <%= label_tag :search, '<i class="fa fa-search fa-lg fa-fw"></i>'.html_safe %>
                <%= text_field_tag :search, params[:search], :utf8 => nil %>
              <% end %>
             </div>
           </li>
             </ul>
          </div>
          <div class="title-bar-right">
            <ul class="menu">
              <% if current_user %>
                <li><%= link_to current_user.username, user_path(current_user.id) %></li>
                <li><%= link_to '<i class="fa fa-sign-out fa-fw"></i>'.html_safe, :logout, method: :post %></li>
              <% end %>
            </ul>
          </div>
        </div>
        
        <div class="row">
          <div class="small-12 columns">
            
            <% flash.each do |key,value| %>
              <%= content_tag :div, value, class: "callout #{key}" %>
            <% end %>
            

            
            <!-- Page content -->
            <%= yield %>
             
         
           </div>
         </div>
        
        
      </div>
    </div>
  </div>


  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'favicon.ico' %>

    <title><%= content_for?(:title) ? yield(:title) : "SEO Report" %></title>

    <%= stylesheet_link_tag    "application", media: "screen, print" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Oswald|Roboto:400,400italic|Roboto+Condensed' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  </head>

  <body class="splash">
    
    
        <div class="row">
          <div class="medium-10 medium-offset-1 columns">
            
            <% flash.each do |key,value| %>
              <%= content_tag :div, value, class: "callout #{key}" %>
            <% end %>
            
            <div class="callout card">
              <div class="callout-header">
                <div class="row">
                    <div class="small-6 columns">
                      <%= link_to(image_tag("logo-dark.png", :alt => "logo", :title => "Home"), "/") %>
                    </div>
                    
                    <div class="small-6 columns">
                      <ul class="menu align-right">
                        <li><a id="login" class="active">Log In</a></li>
                        <li><a id="signup">Sign Up</a></li>
                      </ul>
                    </div>
                  
                </div>
              </div>
              <div class="callout-body text-center">
            
                <div class="login">
                  <%= yield %>
                </div>
                
                <div class="signup">
                  <%= render 'users/signup' %>
                </div>
                
                

              </div>
            </div>
         
             
         
           </div>
         </div>
         
         <script>
            $('.callout-body .signup').hide();
              
           $('.menu #login').click(function() {
              $('.menu a').removeClass('active');
              $('.menu #login').addClass('active');
              
              $('.callout-body .login').show();
              $('.callout-body .signup').hide();
              
            });
            
           $('.menu #signup').click(function() {
              $('.menu a').removeClass('active');
              $('.menu #signup').addClass('active');
              
              $('.callout-body .login').hide();
              $('.callout-body .signup').show();
            });
           
         </script>

  </body>
</html>

app/views/layouts/report.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'favicon.ico' %>

    <title><%= content_for?(:title) ? yield(:title) : "SEO Report" %></title>

    <%= stylesheet_link_tag    "application", media: "screen, print" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Oswald|Roboto:400,400italic|Roboto+Condensed' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  </head>

  <body class="report">
        
        <a class="printBtn" onclick="printFunct()">Print this Report</a>
      
        <!-- Page content -->
        <%= yield %>
        
        <script>
        function printFunct() {
            window.print();
        }
        </script>
      
  </body>
</html>